language: node_js

install: 
  - npm install ci

script:
  - npm build 

deploy:
  provider: heroku
  api_key: 0c248be2-00ee-45be-8a1c-bbc8cb4ba53b

notifications:
  slack: is-utn-2019:C8jMW51RUaWN8bgFivDvPmYh
