language: node_js

install: 
  - npm install ci

script:
  - npm sonar-scanner
  - npm build 

deploy:
  provider: heroku
  api_key: $HEROKU_TOKEN

notifications:
  slack: is-utn-2019:C8jMW51RUaWN8bgFivDvPmYh

addons:
  sonarcloud:
    organization: "ing-sw" 
    token:
      secure: $SONAR_TOKEN
